// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"cscd-bds/store/ent"
)

type FeishuUser struct {
	OpenID    string `json:"openId"`
	Name      string `json:"name"`
	AvatarURL string `json:"avatarUrl"`
}

type GeoJSON struct {
	Type        string    `json:"type"`
	Coordinates []float64 `json:"coordinates"`
}

type Location struct {
	FullAddress string        `json:"fullAddress"`
	Province    *ent.Province `json:"province"`
	City        *ent.City     `json:"city,omitempty"`
	District    *ent.District `json:"district"`
}

type Session struct {
	UserID        string `json:"userId"`
	Name          string `json:"name"`
	Username      string `json:"username"`
	Email         string `json:"email"`
	AvatarURL     string `json:"avatarUrl"`
	IsAdmin       bool   `json:"isAdmin"`
	IsSuperAdmin  bool   `json:"isSuperAdmin"`
	IsCeo         bool   `json:"isCeo"`
	HasMapAccess  bool   `json:"hasMapAccess"`
	HasEditAccess bool   `json:"hasEditAccess"`
}
