// Code generated by ent, DO NOT EDIT.

package customerprofile

import (
	"cscd-bds/store/ent/predicate"
	"cscd-bds/store/ent/schema/xid"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldName, v))
}

// ApprovalStatus applies equality check predicate on the "approval_status" field. It's identical to ApprovalStatusEQ.
func ApprovalStatus(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldApprovalStatus, v))
}

// OwnerType applies equality check predicate on the "owner_type" field. It's identical to OwnerTypeEQ.
func OwnerType(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldOwnerType, v))
}

// Industry applies equality check predicate on the "industry" field. It's identical to IndustryEQ.
func Industry(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldIndustry, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldSize, v))
}

// ContactPerson applies equality check predicate on the "contact_person" field. It's identical to ContactPersonEQ.
func ContactPerson(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPerson, v))
}

// ContactPersonPosition applies equality check predicate on the "contact_person_position" field. It's identical to ContactPersonPositionEQ.
func ContactPersonPosition(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPersonPosition, v))
}

// ContactPersonPhone applies equality check predicate on the "contact_person_phone" field. It's identical to ContactPersonPhoneEQ.
func ContactPersonPhone(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPersonPhone, v))
}

// ContactPersonEmail applies equality check predicate on the "contact_person_email" field. It's identical to ContactPersonEmailEQ.
func ContactPersonEmail(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPersonEmail, v))
}

// SalesID applies equality check predicate on the "sales_id" field. It's identical to SalesIDEQ.
func SalesID(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldSalesID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldCustomerID, v))
}

// CreatedByID applies equality check predicate on the "created_by_id" field. It's identical to CreatedByIDEQ.
func CreatedByID(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldCreatedByID, v))
}

// ApproverID applies equality check predicate on the "approver_id" field. It's identical to ApproverIDEQ.
func ApproverID(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldApproverID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldName, v))
}

// ApprovalStatusEQ applies the EQ predicate on the "approval_status" field.
func ApprovalStatusEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldApprovalStatus, v))
}

// ApprovalStatusNEQ applies the NEQ predicate on the "approval_status" field.
func ApprovalStatusNEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldApprovalStatus, v))
}

// ApprovalStatusIn applies the In predicate on the "approval_status" field.
func ApprovalStatusIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldApprovalStatus, vs...))
}

// ApprovalStatusNotIn applies the NotIn predicate on the "approval_status" field.
func ApprovalStatusNotIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldApprovalStatus, vs...))
}

// ApprovalStatusGT applies the GT predicate on the "approval_status" field.
func ApprovalStatusGT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldApprovalStatus, v))
}

// ApprovalStatusGTE applies the GTE predicate on the "approval_status" field.
func ApprovalStatusGTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldApprovalStatus, v))
}

// ApprovalStatusLT applies the LT predicate on the "approval_status" field.
func ApprovalStatusLT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldApprovalStatus, v))
}

// ApprovalStatusLTE applies the LTE predicate on the "approval_status" field.
func ApprovalStatusLTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldApprovalStatus, v))
}

// OwnerTypeEQ applies the EQ predicate on the "owner_type" field.
func OwnerTypeEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldOwnerType, v))
}

// OwnerTypeNEQ applies the NEQ predicate on the "owner_type" field.
func OwnerTypeNEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldOwnerType, v))
}

// OwnerTypeIn applies the In predicate on the "owner_type" field.
func OwnerTypeIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldOwnerType, vs...))
}

// OwnerTypeNotIn applies the NotIn predicate on the "owner_type" field.
func OwnerTypeNotIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldOwnerType, vs...))
}

// OwnerTypeGT applies the GT predicate on the "owner_type" field.
func OwnerTypeGT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldOwnerType, v))
}

// OwnerTypeGTE applies the GTE predicate on the "owner_type" field.
func OwnerTypeGTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldOwnerType, v))
}

// OwnerTypeLT applies the LT predicate on the "owner_type" field.
func OwnerTypeLT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldOwnerType, v))
}

// OwnerTypeLTE applies the LTE predicate on the "owner_type" field.
func OwnerTypeLTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldOwnerType, v))
}

// OwnerTypeIsNil applies the IsNil predicate on the "owner_type" field.
func OwnerTypeIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldOwnerType))
}

// OwnerTypeNotNil applies the NotNil predicate on the "owner_type" field.
func OwnerTypeNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldOwnerType))
}

// IndustryEQ applies the EQ predicate on the "industry" field.
func IndustryEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldIndustry, v))
}

// IndustryNEQ applies the NEQ predicate on the "industry" field.
func IndustryNEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldIndustry, v))
}

// IndustryIn applies the In predicate on the "industry" field.
func IndustryIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldIndustry, vs...))
}

// IndustryNotIn applies the NotIn predicate on the "industry" field.
func IndustryNotIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldIndustry, vs...))
}

// IndustryGT applies the GT predicate on the "industry" field.
func IndustryGT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldIndustry, v))
}

// IndustryGTE applies the GTE predicate on the "industry" field.
func IndustryGTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldIndustry, v))
}

// IndustryLT applies the LT predicate on the "industry" field.
func IndustryLT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldIndustry, v))
}

// IndustryLTE applies the LTE predicate on the "industry" field.
func IndustryLTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldIndustry, v))
}

// IndustryIsNil applies the IsNil predicate on the "industry" field.
func IndustryIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldIndustry))
}

// IndustryNotNil applies the NotNil predicate on the "industry" field.
func IndustryNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldIndustry))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldSize))
}

// ContactPersonEQ applies the EQ predicate on the "contact_person" field.
func ContactPersonEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPerson, v))
}

// ContactPersonNEQ applies the NEQ predicate on the "contact_person" field.
func ContactPersonNEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldContactPerson, v))
}

// ContactPersonIn applies the In predicate on the "contact_person" field.
func ContactPersonIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldContactPerson, vs...))
}

// ContactPersonNotIn applies the NotIn predicate on the "contact_person" field.
func ContactPersonNotIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldContactPerson, vs...))
}

// ContactPersonGT applies the GT predicate on the "contact_person" field.
func ContactPersonGT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldContactPerson, v))
}

// ContactPersonGTE applies the GTE predicate on the "contact_person" field.
func ContactPersonGTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldContactPerson, v))
}

// ContactPersonLT applies the LT predicate on the "contact_person" field.
func ContactPersonLT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldContactPerson, v))
}

// ContactPersonLTE applies the LTE predicate on the "contact_person" field.
func ContactPersonLTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldContactPerson, v))
}

// ContactPersonContains applies the Contains predicate on the "contact_person" field.
func ContactPersonContains(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContains(FieldContactPerson, v))
}

// ContactPersonHasPrefix applies the HasPrefix predicate on the "contact_person" field.
func ContactPersonHasPrefix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldContactPerson, v))
}

// ContactPersonHasSuffix applies the HasSuffix predicate on the "contact_person" field.
func ContactPersonHasSuffix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldContactPerson, v))
}

// ContactPersonIsNil applies the IsNil predicate on the "contact_person" field.
func ContactPersonIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldContactPerson))
}

// ContactPersonNotNil applies the NotNil predicate on the "contact_person" field.
func ContactPersonNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldContactPerson))
}

// ContactPersonEqualFold applies the EqualFold predicate on the "contact_person" field.
func ContactPersonEqualFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldContactPerson, v))
}

// ContactPersonContainsFold applies the ContainsFold predicate on the "contact_person" field.
func ContactPersonContainsFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldContactPerson, v))
}

// ContactPersonPositionEQ applies the EQ predicate on the "contact_person_position" field.
func ContactPersonPositionEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPersonPosition, v))
}

// ContactPersonPositionNEQ applies the NEQ predicate on the "contact_person_position" field.
func ContactPersonPositionNEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldContactPersonPosition, v))
}

// ContactPersonPositionIn applies the In predicate on the "contact_person_position" field.
func ContactPersonPositionIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldContactPersonPosition, vs...))
}

// ContactPersonPositionNotIn applies the NotIn predicate on the "contact_person_position" field.
func ContactPersonPositionNotIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldContactPersonPosition, vs...))
}

// ContactPersonPositionGT applies the GT predicate on the "contact_person_position" field.
func ContactPersonPositionGT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldContactPersonPosition, v))
}

// ContactPersonPositionGTE applies the GTE predicate on the "contact_person_position" field.
func ContactPersonPositionGTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldContactPersonPosition, v))
}

// ContactPersonPositionLT applies the LT predicate on the "contact_person_position" field.
func ContactPersonPositionLT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldContactPersonPosition, v))
}

// ContactPersonPositionLTE applies the LTE predicate on the "contact_person_position" field.
func ContactPersonPositionLTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldContactPersonPosition, v))
}

// ContactPersonPositionContains applies the Contains predicate on the "contact_person_position" field.
func ContactPersonPositionContains(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContains(FieldContactPersonPosition, v))
}

// ContactPersonPositionHasPrefix applies the HasPrefix predicate on the "contact_person_position" field.
func ContactPersonPositionHasPrefix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldContactPersonPosition, v))
}

// ContactPersonPositionHasSuffix applies the HasSuffix predicate on the "contact_person_position" field.
func ContactPersonPositionHasSuffix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldContactPersonPosition, v))
}

// ContactPersonPositionIsNil applies the IsNil predicate on the "contact_person_position" field.
func ContactPersonPositionIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldContactPersonPosition))
}

// ContactPersonPositionNotNil applies the NotNil predicate on the "contact_person_position" field.
func ContactPersonPositionNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldContactPersonPosition))
}

// ContactPersonPositionEqualFold applies the EqualFold predicate on the "contact_person_position" field.
func ContactPersonPositionEqualFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldContactPersonPosition, v))
}

// ContactPersonPositionContainsFold applies the ContainsFold predicate on the "contact_person_position" field.
func ContactPersonPositionContainsFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldContactPersonPosition, v))
}

// ContactPersonPhoneEQ applies the EQ predicate on the "contact_person_phone" field.
func ContactPersonPhoneEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPersonPhone, v))
}

// ContactPersonPhoneNEQ applies the NEQ predicate on the "contact_person_phone" field.
func ContactPersonPhoneNEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldContactPersonPhone, v))
}

// ContactPersonPhoneIn applies the In predicate on the "contact_person_phone" field.
func ContactPersonPhoneIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldContactPersonPhone, vs...))
}

// ContactPersonPhoneNotIn applies the NotIn predicate on the "contact_person_phone" field.
func ContactPersonPhoneNotIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldContactPersonPhone, vs...))
}

// ContactPersonPhoneGT applies the GT predicate on the "contact_person_phone" field.
func ContactPersonPhoneGT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldContactPersonPhone, v))
}

// ContactPersonPhoneGTE applies the GTE predicate on the "contact_person_phone" field.
func ContactPersonPhoneGTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldContactPersonPhone, v))
}

// ContactPersonPhoneLT applies the LT predicate on the "contact_person_phone" field.
func ContactPersonPhoneLT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldContactPersonPhone, v))
}

// ContactPersonPhoneLTE applies the LTE predicate on the "contact_person_phone" field.
func ContactPersonPhoneLTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldContactPersonPhone, v))
}

// ContactPersonPhoneContains applies the Contains predicate on the "contact_person_phone" field.
func ContactPersonPhoneContains(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContains(FieldContactPersonPhone, v))
}

// ContactPersonPhoneHasPrefix applies the HasPrefix predicate on the "contact_person_phone" field.
func ContactPersonPhoneHasPrefix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldContactPersonPhone, v))
}

// ContactPersonPhoneHasSuffix applies the HasSuffix predicate on the "contact_person_phone" field.
func ContactPersonPhoneHasSuffix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldContactPersonPhone, v))
}

// ContactPersonPhoneIsNil applies the IsNil predicate on the "contact_person_phone" field.
func ContactPersonPhoneIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldContactPersonPhone))
}

// ContactPersonPhoneNotNil applies the NotNil predicate on the "contact_person_phone" field.
func ContactPersonPhoneNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldContactPersonPhone))
}

// ContactPersonPhoneEqualFold applies the EqualFold predicate on the "contact_person_phone" field.
func ContactPersonPhoneEqualFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldContactPersonPhone, v))
}

// ContactPersonPhoneContainsFold applies the ContainsFold predicate on the "contact_person_phone" field.
func ContactPersonPhoneContainsFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldContactPersonPhone, v))
}

// ContactPersonEmailEQ applies the EQ predicate on the "contact_person_email" field.
func ContactPersonEmailEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldContactPersonEmail, v))
}

// ContactPersonEmailNEQ applies the NEQ predicate on the "contact_person_email" field.
func ContactPersonEmailNEQ(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldContactPersonEmail, v))
}

// ContactPersonEmailIn applies the In predicate on the "contact_person_email" field.
func ContactPersonEmailIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldContactPersonEmail, vs...))
}

// ContactPersonEmailNotIn applies the NotIn predicate on the "contact_person_email" field.
func ContactPersonEmailNotIn(vs ...string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldContactPersonEmail, vs...))
}

// ContactPersonEmailGT applies the GT predicate on the "contact_person_email" field.
func ContactPersonEmailGT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldContactPersonEmail, v))
}

// ContactPersonEmailGTE applies the GTE predicate on the "contact_person_email" field.
func ContactPersonEmailGTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldContactPersonEmail, v))
}

// ContactPersonEmailLT applies the LT predicate on the "contact_person_email" field.
func ContactPersonEmailLT(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldContactPersonEmail, v))
}

// ContactPersonEmailLTE applies the LTE predicate on the "contact_person_email" field.
func ContactPersonEmailLTE(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldContactPersonEmail, v))
}

// ContactPersonEmailContains applies the Contains predicate on the "contact_person_email" field.
func ContactPersonEmailContains(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContains(FieldContactPersonEmail, v))
}

// ContactPersonEmailHasPrefix applies the HasPrefix predicate on the "contact_person_email" field.
func ContactPersonEmailHasPrefix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldContactPersonEmail, v))
}

// ContactPersonEmailHasSuffix applies the HasSuffix predicate on the "contact_person_email" field.
func ContactPersonEmailHasSuffix(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldContactPersonEmail, v))
}

// ContactPersonEmailIsNil applies the IsNil predicate on the "contact_person_email" field.
func ContactPersonEmailIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldContactPersonEmail))
}

// ContactPersonEmailNotNil applies the NotNil predicate on the "contact_person_email" field.
func ContactPersonEmailNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldContactPersonEmail))
}

// ContactPersonEmailEqualFold applies the EqualFold predicate on the "contact_person_email" field.
func ContactPersonEmailEqualFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldContactPersonEmail, v))
}

// ContactPersonEmailContainsFold applies the ContainsFold predicate on the "contact_person_email" field.
func ContactPersonEmailContainsFold(v string) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldContactPersonEmail, v))
}

// SalesIDEQ applies the EQ predicate on the "sales_id" field.
func SalesIDEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldSalesID, v))
}

// SalesIDNEQ applies the NEQ predicate on the "sales_id" field.
func SalesIDNEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldSalesID, v))
}

// SalesIDIn applies the In predicate on the "sales_id" field.
func SalesIDIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldSalesID, vs...))
}

// SalesIDNotIn applies the NotIn predicate on the "sales_id" field.
func SalesIDNotIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldSalesID, vs...))
}

// SalesIDGT applies the GT predicate on the "sales_id" field.
func SalesIDGT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldSalesID, v))
}

// SalesIDGTE applies the GTE predicate on the "sales_id" field.
func SalesIDGTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldSalesID, v))
}

// SalesIDLT applies the LT predicate on the "sales_id" field.
func SalesIDLT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldSalesID, v))
}

// SalesIDLTE applies the LTE predicate on the "sales_id" field.
func SalesIDLTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldSalesID, v))
}

// SalesIDContains applies the Contains predicate on the "sales_id" field.
func SalesIDContains(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContains(FieldSalesID, vc))
}

// SalesIDHasPrefix applies the HasPrefix predicate on the "sales_id" field.
func SalesIDHasPrefix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldSalesID, vc))
}

// SalesIDHasSuffix applies the HasSuffix predicate on the "sales_id" field.
func SalesIDHasSuffix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldSalesID, vc))
}

// SalesIDIsNil applies the IsNil predicate on the "sales_id" field.
func SalesIDIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldSalesID))
}

// SalesIDNotNil applies the NotNil predicate on the "sales_id" field.
func SalesIDNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldSalesID))
}

// SalesIDEqualFold applies the EqualFold predicate on the "sales_id" field.
func SalesIDEqualFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldSalesID, vc))
}

// SalesIDContainsFold applies the ContainsFold predicate on the "sales_id" field.
func SalesIDContainsFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldSalesID, vc))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContains(FieldCustomerID, vc))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldCustomerID, vc))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldCustomerID, vc))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldCustomerID, vc))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldCustomerID, vc))
}

// CreatedByIDEQ applies the EQ predicate on the "created_by_id" field.
func CreatedByIDEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldCreatedByID, v))
}

// CreatedByIDNEQ applies the NEQ predicate on the "created_by_id" field.
func CreatedByIDNEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldCreatedByID, v))
}

// CreatedByIDIn applies the In predicate on the "created_by_id" field.
func CreatedByIDIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldCreatedByID, vs...))
}

// CreatedByIDNotIn applies the NotIn predicate on the "created_by_id" field.
func CreatedByIDNotIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldCreatedByID, vs...))
}

// CreatedByIDGT applies the GT predicate on the "created_by_id" field.
func CreatedByIDGT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldCreatedByID, v))
}

// CreatedByIDGTE applies the GTE predicate on the "created_by_id" field.
func CreatedByIDGTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldCreatedByID, v))
}

// CreatedByIDLT applies the LT predicate on the "created_by_id" field.
func CreatedByIDLT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldCreatedByID, v))
}

// CreatedByIDLTE applies the LTE predicate on the "created_by_id" field.
func CreatedByIDLTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldCreatedByID, v))
}

// CreatedByIDContains applies the Contains predicate on the "created_by_id" field.
func CreatedByIDContains(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContains(FieldCreatedByID, vc))
}

// CreatedByIDHasPrefix applies the HasPrefix predicate on the "created_by_id" field.
func CreatedByIDHasPrefix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldCreatedByID, vc))
}

// CreatedByIDHasSuffix applies the HasSuffix predicate on the "created_by_id" field.
func CreatedByIDHasSuffix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldCreatedByID, vc))
}

// CreatedByIDIsNil applies the IsNil predicate on the "created_by_id" field.
func CreatedByIDIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldCreatedByID))
}

// CreatedByIDNotNil applies the NotNil predicate on the "created_by_id" field.
func CreatedByIDNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldCreatedByID))
}

// CreatedByIDEqualFold applies the EqualFold predicate on the "created_by_id" field.
func CreatedByIDEqualFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldCreatedByID, vc))
}

// CreatedByIDContainsFold applies the ContainsFold predicate on the "created_by_id" field.
func CreatedByIDContainsFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldCreatedByID, vc))
}

// ApproverIDEQ applies the EQ predicate on the "approver_id" field.
func ApproverIDEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldEQ(FieldApproverID, v))
}

// ApproverIDNEQ applies the NEQ predicate on the "approver_id" field.
func ApproverIDNEQ(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNEQ(FieldApproverID, v))
}

// ApproverIDIn applies the In predicate on the "approver_id" field.
func ApproverIDIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIn(FieldApproverID, vs...))
}

// ApproverIDNotIn applies the NotIn predicate on the "approver_id" field.
func ApproverIDNotIn(vs ...xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotIn(FieldApproverID, vs...))
}

// ApproverIDGT applies the GT predicate on the "approver_id" field.
func ApproverIDGT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGT(FieldApproverID, v))
}

// ApproverIDGTE applies the GTE predicate on the "approver_id" field.
func ApproverIDGTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldGTE(FieldApproverID, v))
}

// ApproverIDLT applies the LT predicate on the "approver_id" field.
func ApproverIDLT(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLT(FieldApproverID, v))
}

// ApproverIDLTE applies the LTE predicate on the "approver_id" field.
func ApproverIDLTE(v xid.ID) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldLTE(FieldApproverID, v))
}

// ApproverIDContains applies the Contains predicate on the "approver_id" field.
func ApproverIDContains(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContains(FieldApproverID, vc))
}

// ApproverIDHasPrefix applies the HasPrefix predicate on the "approver_id" field.
func ApproverIDHasPrefix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasPrefix(FieldApproverID, vc))
}

// ApproverIDHasSuffix applies the HasSuffix predicate on the "approver_id" field.
func ApproverIDHasSuffix(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldHasSuffix(FieldApproverID, vc))
}

// ApproverIDIsNil applies the IsNil predicate on the "approver_id" field.
func ApproverIDIsNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldIsNull(FieldApproverID))
}

// ApproverIDNotNil applies the NotNil predicate on the "approver_id" field.
func ApproverIDNotNil() predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.FieldNotNull(FieldApproverID))
}

// ApproverIDEqualFold applies the EqualFold predicate on the "approver_id" field.
func ApproverIDEqualFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldEqualFold(FieldApproverID, vc))
}

// ApproverIDContainsFold applies the ContainsFold predicate on the "approver_id" field.
func ApproverIDContainsFold(v xid.ID) predicate.CustomerProfile {
	vc := string(v)
	return predicate.CustomerProfile(sql.FieldContainsFold(FieldApproverID, vc))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedBy applies the HasEdge predicate on the "created_by" edge.
func HasCreatedBy() predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatedByTable, CreatedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByWith applies the HasEdge predicate on the "created_by" edge with a given conditions (other predicates).
func HasCreatedByWith(preds ...predicate.User) predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := newCreatedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApprover applies the HasEdge predicate on the "approver" edge.
func HasApprover() predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApproverTable, ApproverColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApproverWith applies the HasEdge predicate on the "approver" edge with a given conditions (other predicates).
func HasApproverWith(preds ...predicate.User) predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := newApproverStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSales applies the HasEdge predicate on the "sales" edge.
func HasSales() predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SalesTable, SalesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSalesWith applies the HasEdge predicate on the "sales" edge with a given conditions (other predicates).
func HasSalesWith(preds ...predicate.User) predicate.CustomerProfile {
	return predicate.CustomerProfile(func(s *sql.Selector) {
		step := newSalesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerProfile) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerProfile) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerProfile) predicate.CustomerProfile {
	return predicate.CustomerProfile(sql.NotPredicates(p))
}
