// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cscd-bds/store/ent/operation"
	"cscd-bds/store/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OperationUpdate is the builder for updating Operation entities.
type OperationUpdate struct {
	config
	hooks    []Hook
	mutation *OperationMutation
}

// Where appends a list predicates to the OperationUpdate builder.
func (ou *OperationUpdate) Where(ps ...predicate.Operation) *OperationUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OperationUpdate) SetUpdatedAt(t time.Time) *OperationUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// SetCjeYs sets the "cje_ys" field.
func (ou *OperationUpdate) SetCjeYs(f float64) *OperationUpdate {
	ou.mutation.ResetCjeYs()
	ou.mutation.SetCjeYs(f)
	return ou
}

// SetNillableCjeYs sets the "cje_ys" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableCjeYs(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetCjeYs(*f)
	}
	return ou
}

// AddCjeYs adds f to the "cje_ys" field.
func (ou *OperationUpdate) AddCjeYs(f float64) *OperationUpdate {
	ou.mutation.AddCjeYs(f)
	return ou
}

// ClearCjeYs clears the value of the "cje_ys" field.
func (ou *OperationUpdate) ClearCjeYs() *OperationUpdate {
	ou.mutation.ClearCjeYs()
	return ou
}

// SetCjeLj sets the "cje_lj" field.
func (ou *OperationUpdate) SetCjeLj(f float64) *OperationUpdate {
	ou.mutation.ResetCjeLj()
	ou.mutation.SetCjeLj(f)
	return ou
}

// SetNillableCjeLj sets the "cje_lj" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableCjeLj(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetCjeLj(*f)
	}
	return ou
}

// AddCjeLj adds f to the "cje_lj" field.
func (ou *OperationUpdate) AddCjeLj(f float64) *OperationUpdate {
	ou.mutation.AddCjeLj(f)
	return ou
}

// ClearCjeLj clears the value of the "cje_lj" field.
func (ou *OperationUpdate) ClearCjeLj() *OperationUpdate {
	ou.mutation.ClearCjeLj()
	return ou
}

// SetYyeYs sets the "yye_ys" field.
func (ou *OperationUpdate) SetYyeYs(f float64) *OperationUpdate {
	ou.mutation.ResetYyeYs()
	ou.mutation.SetYyeYs(f)
	return ou
}

// SetNillableYyeYs sets the "yye_ys" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableYyeYs(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetYyeYs(*f)
	}
	return ou
}

// AddYyeYs adds f to the "yye_ys" field.
func (ou *OperationUpdate) AddYyeYs(f float64) *OperationUpdate {
	ou.mutation.AddYyeYs(f)
	return ou
}

// ClearYyeYs clears the value of the "yye_ys" field.
func (ou *OperationUpdate) ClearYyeYs() *OperationUpdate {
	ou.mutation.ClearYyeYs()
	return ou
}

// SetYyeLj sets the "yye_lj" field.
func (ou *OperationUpdate) SetYyeLj(f float64) *OperationUpdate {
	ou.mutation.ResetYyeLj()
	ou.mutation.SetYyeLj(f)
	return ou
}

// SetNillableYyeLj sets the "yye_lj" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableYyeLj(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetYyeLj(*f)
	}
	return ou
}

// AddYyeLj adds f to the "yye_lj" field.
func (ou *OperationUpdate) AddYyeLj(f float64) *OperationUpdate {
	ou.mutation.AddYyeLj(f)
	return ou
}

// ClearYyeLj clears the value of the "yye_lj" field.
func (ou *OperationUpdate) ClearYyeLj() *OperationUpdate {
	ou.mutation.ClearYyeLj()
	return ou
}

// SetXjlYs sets the "xjl_ys" field.
func (ou *OperationUpdate) SetXjlYs(f float64) *OperationUpdate {
	ou.mutation.ResetXjlYs()
	ou.mutation.SetXjlYs(f)
	return ou
}

// SetNillableXjlYs sets the "xjl_ys" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableXjlYs(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetXjlYs(*f)
	}
	return ou
}

// AddXjlYs adds f to the "xjl_ys" field.
func (ou *OperationUpdate) AddXjlYs(f float64) *OperationUpdate {
	ou.mutation.AddXjlYs(f)
	return ou
}

// ClearXjlYs clears the value of the "xjl_ys" field.
func (ou *OperationUpdate) ClearXjlYs() *OperationUpdate {
	ou.mutation.ClearXjlYs()
	return ou
}

// SetXjlLj sets the "xjl_lj" field.
func (ou *OperationUpdate) SetXjlLj(f float64) *OperationUpdate {
	ou.mutation.ResetXjlLj()
	ou.mutation.SetXjlLj(f)
	return ou
}

// SetNillableXjlLj sets the "xjl_lj" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableXjlLj(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetXjlLj(*f)
	}
	return ou
}

// AddXjlLj adds f to the "xjl_lj" field.
func (ou *OperationUpdate) AddXjlLj(f float64) *OperationUpdate {
	ou.mutation.AddXjlLj(f)
	return ou
}

// ClearXjlLj clears the value of the "xjl_lj" field.
func (ou *OperationUpdate) ClearXjlLj() *OperationUpdate {
	ou.mutation.ClearXjlLj()
	return ou
}

// SetXmglf sets the "xmglf" field.
func (ou *OperationUpdate) SetXmglf(f float64) *OperationUpdate {
	ou.mutation.ResetXmglf()
	ou.mutation.SetXmglf(f)
	return ou
}

// SetNillableXmglf sets the "xmglf" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableXmglf(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetXmglf(*f)
	}
	return ou
}

// AddXmglf adds f to the "xmglf" field.
func (ou *OperationUpdate) AddXmglf(f float64) *OperationUpdate {
	ou.mutation.AddXmglf(f)
	return ou
}

// ClearXmglf clears the value of the "xmglf" field.
func (ou *OperationUpdate) ClearXmglf() *OperationUpdate {
	ou.mutation.ClearXmglf()
	return ou
}

// SetXmsjf sets the "xmsjf" field.
func (ou *OperationUpdate) SetXmsjf(f float64) *OperationUpdate {
	ou.mutation.ResetXmsjf()
	ou.mutation.SetXmsjf(f)
	return ou
}

// SetNillableXmsjf sets the "xmsjf" field if the given value is not nil.
func (ou *OperationUpdate) SetNillableXmsjf(f *float64) *OperationUpdate {
	if f != nil {
		ou.SetXmsjf(*f)
	}
	return ou
}

// AddXmsjf adds f to the "xmsjf" field.
func (ou *OperationUpdate) AddXmsjf(f float64) *OperationUpdate {
	ou.mutation.AddXmsjf(f)
	return ou
}

// ClearXmsjf clears the value of the "xmsjf" field.
func (ou *OperationUpdate) ClearXmsjf() *OperationUpdate {
	ou.mutation.ClearXmsjf()
	return ou
}

// Mutation returns the OperationMutation object of the builder.
func (ou *OperationUpdate) Mutation() *OperationMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OperationUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OperationUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OperationUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OperationUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OperationUpdate) defaults() {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		v := operation.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
}

func (ou *OperationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(operation.Table, operation.Columns, sqlgraph.NewFieldSpec(operation.FieldID, field.TypeString))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(operation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.CjeYs(); ok {
		_spec.SetField(operation.FieldCjeYs, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedCjeYs(); ok {
		_spec.AddField(operation.FieldCjeYs, field.TypeFloat64, value)
	}
	if ou.mutation.CjeYsCleared() {
		_spec.ClearField(operation.FieldCjeYs, field.TypeFloat64)
	}
	if value, ok := ou.mutation.CjeLj(); ok {
		_spec.SetField(operation.FieldCjeLj, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedCjeLj(); ok {
		_spec.AddField(operation.FieldCjeLj, field.TypeFloat64, value)
	}
	if ou.mutation.CjeLjCleared() {
		_spec.ClearField(operation.FieldCjeLj, field.TypeFloat64)
	}
	if value, ok := ou.mutation.YyeYs(); ok {
		_spec.SetField(operation.FieldYyeYs, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedYyeYs(); ok {
		_spec.AddField(operation.FieldYyeYs, field.TypeFloat64, value)
	}
	if ou.mutation.YyeYsCleared() {
		_spec.ClearField(operation.FieldYyeYs, field.TypeFloat64)
	}
	if value, ok := ou.mutation.YyeLj(); ok {
		_spec.SetField(operation.FieldYyeLj, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedYyeLj(); ok {
		_spec.AddField(operation.FieldYyeLj, field.TypeFloat64, value)
	}
	if ou.mutation.YyeLjCleared() {
		_spec.ClearField(operation.FieldYyeLj, field.TypeFloat64)
	}
	if value, ok := ou.mutation.XjlYs(); ok {
		_spec.SetField(operation.FieldXjlYs, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedXjlYs(); ok {
		_spec.AddField(operation.FieldXjlYs, field.TypeFloat64, value)
	}
	if ou.mutation.XjlYsCleared() {
		_spec.ClearField(operation.FieldXjlYs, field.TypeFloat64)
	}
	if value, ok := ou.mutation.XjlLj(); ok {
		_spec.SetField(operation.FieldXjlLj, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedXjlLj(); ok {
		_spec.AddField(operation.FieldXjlLj, field.TypeFloat64, value)
	}
	if ou.mutation.XjlLjCleared() {
		_spec.ClearField(operation.FieldXjlLj, field.TypeFloat64)
	}
	if value, ok := ou.mutation.Xmglf(); ok {
		_spec.SetField(operation.FieldXmglf, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedXmglf(); ok {
		_spec.AddField(operation.FieldXmglf, field.TypeFloat64, value)
	}
	if ou.mutation.XmglfCleared() {
		_spec.ClearField(operation.FieldXmglf, field.TypeFloat64)
	}
	if value, ok := ou.mutation.Xmsjf(); ok {
		_spec.SetField(operation.FieldXmsjf, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedXmsjf(); ok {
		_spec.AddField(operation.FieldXmsjf, field.TypeFloat64, value)
	}
	if ou.mutation.XmsjfCleared() {
		_spec.ClearField(operation.FieldXmsjf, field.TypeFloat64)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OperationUpdateOne is the builder for updating a single Operation entity.
type OperationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OperationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OperationUpdateOne) SetUpdatedAt(t time.Time) *OperationUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// SetCjeYs sets the "cje_ys" field.
func (ouo *OperationUpdateOne) SetCjeYs(f float64) *OperationUpdateOne {
	ouo.mutation.ResetCjeYs()
	ouo.mutation.SetCjeYs(f)
	return ouo
}

// SetNillableCjeYs sets the "cje_ys" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableCjeYs(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetCjeYs(*f)
	}
	return ouo
}

// AddCjeYs adds f to the "cje_ys" field.
func (ouo *OperationUpdateOne) AddCjeYs(f float64) *OperationUpdateOne {
	ouo.mutation.AddCjeYs(f)
	return ouo
}

// ClearCjeYs clears the value of the "cje_ys" field.
func (ouo *OperationUpdateOne) ClearCjeYs() *OperationUpdateOne {
	ouo.mutation.ClearCjeYs()
	return ouo
}

// SetCjeLj sets the "cje_lj" field.
func (ouo *OperationUpdateOne) SetCjeLj(f float64) *OperationUpdateOne {
	ouo.mutation.ResetCjeLj()
	ouo.mutation.SetCjeLj(f)
	return ouo
}

// SetNillableCjeLj sets the "cje_lj" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableCjeLj(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetCjeLj(*f)
	}
	return ouo
}

// AddCjeLj adds f to the "cje_lj" field.
func (ouo *OperationUpdateOne) AddCjeLj(f float64) *OperationUpdateOne {
	ouo.mutation.AddCjeLj(f)
	return ouo
}

// ClearCjeLj clears the value of the "cje_lj" field.
func (ouo *OperationUpdateOne) ClearCjeLj() *OperationUpdateOne {
	ouo.mutation.ClearCjeLj()
	return ouo
}

// SetYyeYs sets the "yye_ys" field.
func (ouo *OperationUpdateOne) SetYyeYs(f float64) *OperationUpdateOne {
	ouo.mutation.ResetYyeYs()
	ouo.mutation.SetYyeYs(f)
	return ouo
}

// SetNillableYyeYs sets the "yye_ys" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableYyeYs(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetYyeYs(*f)
	}
	return ouo
}

// AddYyeYs adds f to the "yye_ys" field.
func (ouo *OperationUpdateOne) AddYyeYs(f float64) *OperationUpdateOne {
	ouo.mutation.AddYyeYs(f)
	return ouo
}

// ClearYyeYs clears the value of the "yye_ys" field.
func (ouo *OperationUpdateOne) ClearYyeYs() *OperationUpdateOne {
	ouo.mutation.ClearYyeYs()
	return ouo
}

// SetYyeLj sets the "yye_lj" field.
func (ouo *OperationUpdateOne) SetYyeLj(f float64) *OperationUpdateOne {
	ouo.mutation.ResetYyeLj()
	ouo.mutation.SetYyeLj(f)
	return ouo
}

// SetNillableYyeLj sets the "yye_lj" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableYyeLj(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetYyeLj(*f)
	}
	return ouo
}

// AddYyeLj adds f to the "yye_lj" field.
func (ouo *OperationUpdateOne) AddYyeLj(f float64) *OperationUpdateOne {
	ouo.mutation.AddYyeLj(f)
	return ouo
}

// ClearYyeLj clears the value of the "yye_lj" field.
func (ouo *OperationUpdateOne) ClearYyeLj() *OperationUpdateOne {
	ouo.mutation.ClearYyeLj()
	return ouo
}

// SetXjlYs sets the "xjl_ys" field.
func (ouo *OperationUpdateOne) SetXjlYs(f float64) *OperationUpdateOne {
	ouo.mutation.ResetXjlYs()
	ouo.mutation.SetXjlYs(f)
	return ouo
}

// SetNillableXjlYs sets the "xjl_ys" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableXjlYs(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetXjlYs(*f)
	}
	return ouo
}

// AddXjlYs adds f to the "xjl_ys" field.
func (ouo *OperationUpdateOne) AddXjlYs(f float64) *OperationUpdateOne {
	ouo.mutation.AddXjlYs(f)
	return ouo
}

// ClearXjlYs clears the value of the "xjl_ys" field.
func (ouo *OperationUpdateOne) ClearXjlYs() *OperationUpdateOne {
	ouo.mutation.ClearXjlYs()
	return ouo
}

// SetXjlLj sets the "xjl_lj" field.
func (ouo *OperationUpdateOne) SetXjlLj(f float64) *OperationUpdateOne {
	ouo.mutation.ResetXjlLj()
	ouo.mutation.SetXjlLj(f)
	return ouo
}

// SetNillableXjlLj sets the "xjl_lj" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableXjlLj(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetXjlLj(*f)
	}
	return ouo
}

// AddXjlLj adds f to the "xjl_lj" field.
func (ouo *OperationUpdateOne) AddXjlLj(f float64) *OperationUpdateOne {
	ouo.mutation.AddXjlLj(f)
	return ouo
}

// ClearXjlLj clears the value of the "xjl_lj" field.
func (ouo *OperationUpdateOne) ClearXjlLj() *OperationUpdateOne {
	ouo.mutation.ClearXjlLj()
	return ouo
}

// SetXmglf sets the "xmglf" field.
func (ouo *OperationUpdateOne) SetXmglf(f float64) *OperationUpdateOne {
	ouo.mutation.ResetXmglf()
	ouo.mutation.SetXmglf(f)
	return ouo
}

// SetNillableXmglf sets the "xmglf" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableXmglf(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetXmglf(*f)
	}
	return ouo
}

// AddXmglf adds f to the "xmglf" field.
func (ouo *OperationUpdateOne) AddXmglf(f float64) *OperationUpdateOne {
	ouo.mutation.AddXmglf(f)
	return ouo
}

// ClearXmglf clears the value of the "xmglf" field.
func (ouo *OperationUpdateOne) ClearXmglf() *OperationUpdateOne {
	ouo.mutation.ClearXmglf()
	return ouo
}

// SetXmsjf sets the "xmsjf" field.
func (ouo *OperationUpdateOne) SetXmsjf(f float64) *OperationUpdateOne {
	ouo.mutation.ResetXmsjf()
	ouo.mutation.SetXmsjf(f)
	return ouo
}

// SetNillableXmsjf sets the "xmsjf" field if the given value is not nil.
func (ouo *OperationUpdateOne) SetNillableXmsjf(f *float64) *OperationUpdateOne {
	if f != nil {
		ouo.SetXmsjf(*f)
	}
	return ouo
}

// AddXmsjf adds f to the "xmsjf" field.
func (ouo *OperationUpdateOne) AddXmsjf(f float64) *OperationUpdateOne {
	ouo.mutation.AddXmsjf(f)
	return ouo
}

// ClearXmsjf clears the value of the "xmsjf" field.
func (ouo *OperationUpdateOne) ClearXmsjf() *OperationUpdateOne {
	ouo.mutation.ClearXmsjf()
	return ouo
}

// Mutation returns the OperationMutation object of the builder.
func (ouo *OperationUpdateOne) Mutation() *OperationMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OperationUpdate builder.
func (ouo *OperationUpdateOne) Where(ps ...predicate.Operation) *OperationUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OperationUpdateOne) Select(field string, fields ...string) *OperationUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Operation entity.
func (ouo *OperationUpdateOne) Save(ctx context.Context) (*Operation, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OperationUpdateOne) SaveX(ctx context.Context) *Operation {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OperationUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OperationUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OperationUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		v := operation.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
}

func (ouo *OperationUpdateOne) sqlSave(ctx context.Context) (_node *Operation, err error) {
	_spec := sqlgraph.NewUpdateSpec(operation.Table, operation.Columns, sqlgraph.NewFieldSpec(operation.FieldID, field.TypeString))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Operation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operation.FieldID)
		for _, f := range fields {
			if !operation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != operation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(operation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.CjeYs(); ok {
		_spec.SetField(operation.FieldCjeYs, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedCjeYs(); ok {
		_spec.AddField(operation.FieldCjeYs, field.TypeFloat64, value)
	}
	if ouo.mutation.CjeYsCleared() {
		_spec.ClearField(operation.FieldCjeYs, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.CjeLj(); ok {
		_spec.SetField(operation.FieldCjeLj, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedCjeLj(); ok {
		_spec.AddField(operation.FieldCjeLj, field.TypeFloat64, value)
	}
	if ouo.mutation.CjeLjCleared() {
		_spec.ClearField(operation.FieldCjeLj, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.YyeYs(); ok {
		_spec.SetField(operation.FieldYyeYs, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedYyeYs(); ok {
		_spec.AddField(operation.FieldYyeYs, field.TypeFloat64, value)
	}
	if ouo.mutation.YyeYsCleared() {
		_spec.ClearField(operation.FieldYyeYs, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.YyeLj(); ok {
		_spec.SetField(operation.FieldYyeLj, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedYyeLj(); ok {
		_spec.AddField(operation.FieldYyeLj, field.TypeFloat64, value)
	}
	if ouo.mutation.YyeLjCleared() {
		_spec.ClearField(operation.FieldYyeLj, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.XjlYs(); ok {
		_spec.SetField(operation.FieldXjlYs, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedXjlYs(); ok {
		_spec.AddField(operation.FieldXjlYs, field.TypeFloat64, value)
	}
	if ouo.mutation.XjlYsCleared() {
		_spec.ClearField(operation.FieldXjlYs, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.XjlLj(); ok {
		_spec.SetField(operation.FieldXjlLj, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedXjlLj(); ok {
		_spec.AddField(operation.FieldXjlLj, field.TypeFloat64, value)
	}
	if ouo.mutation.XjlLjCleared() {
		_spec.ClearField(operation.FieldXjlLj, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.Xmglf(); ok {
		_spec.SetField(operation.FieldXmglf, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedXmglf(); ok {
		_spec.AddField(operation.FieldXmglf, field.TypeFloat64, value)
	}
	if ouo.mutation.XmglfCleared() {
		_spec.ClearField(operation.FieldXmglf, field.TypeFloat64)
	}
	if value, ok := ouo.mutation.Xmsjf(); ok {
		_spec.SetField(operation.FieldXmsjf, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedXmsjf(); ok {
		_spec.AddField(operation.FieldXmsjf, field.TypeFloat64, value)
	}
	if ouo.mutation.XmsjfCleared() {
		_spec.ClearField(operation.FieldXmsjf, field.TypeFloat64)
	}
	_node = &Operation{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
