// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cscd-bds/store/ent/area"
	"cscd-bds/store/ent/city"
	"cscd-bds/store/ent/country"
	"cscd-bds/store/ent/district"
	"cscd-bds/store/ent/predicate"
	"cscd-bds/store/ent/province"
	"cscd-bds/store/ent/schema/xid"
	"cscd-bds/store/ent/tender"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProvinceQuery is the builder for querying Province entities.
type ProvinceQuery struct {
	config
	ctx                *QueryContext
	order              []province.OrderOption
	inters             []Interceptor
	predicates         []predicate.Province
	withDistricts      *DistrictQuery
	withCities         *CityQuery
	withCountry        *CountryQuery
	withTenders        *TenderQuery
	withArea           *AreaQuery
	modifiers          []func(*sql.Selector)
	loadTotal          []func(context.Context, []*Province) error
	withNamedDistricts map[string]*DistrictQuery
	withNamedCities    map[string]*CityQuery
	withNamedTenders   map[string]*TenderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProvinceQuery builder.
func (pq *ProvinceQuery) Where(ps ...predicate.Province) *ProvinceQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *ProvinceQuery) Limit(limit int) *ProvinceQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *ProvinceQuery) Offset(offset int) *ProvinceQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *ProvinceQuery) Unique(unique bool) *ProvinceQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *ProvinceQuery) Order(o ...province.OrderOption) *ProvinceQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryDistricts chains the current query on the "districts" edge.
func (pq *ProvinceQuery) QueryDistricts() *DistrictQuery {
	query := (&DistrictClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(province.Table, province.FieldID, selector),
			sqlgraph.To(district.Table, district.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, province.DistrictsTable, province.DistrictsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCities chains the current query on the "cities" edge.
func (pq *ProvinceQuery) QueryCities() *CityQuery {
	query := (&CityClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(province.Table, province.FieldID, selector),
			sqlgraph.To(city.Table, city.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, province.CitiesTable, province.CitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCountry chains the current query on the "country" edge.
func (pq *ProvinceQuery) QueryCountry() *CountryQuery {
	query := (&CountryClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(province.Table, province.FieldID, selector),
			sqlgraph.To(country.Table, country.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, province.CountryTable, province.CountryColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenders chains the current query on the "tenders" edge.
func (pq *ProvinceQuery) QueryTenders() *TenderQuery {
	query := (&TenderClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(province.Table, province.FieldID, selector),
			sqlgraph.To(tender.Table, tender.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, province.TendersTable, province.TendersColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryArea chains the current query on the "area" edge.
func (pq *ProvinceQuery) QueryArea() *AreaQuery {
	query := (&AreaClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(province.Table, province.FieldID, selector),
			sqlgraph.To(area.Table, area.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, province.AreaTable, province.AreaColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Province entity from the query.
// Returns a *NotFoundError when no Province was found.
func (pq *ProvinceQuery) First(ctx context.Context) (*Province, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{province.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *ProvinceQuery) FirstX(ctx context.Context) *Province {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Province ID from the query.
// Returns a *NotFoundError when no Province ID was found.
func (pq *ProvinceQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{province.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *ProvinceQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Province entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Province entity is found.
// Returns a *NotFoundError when no Province entities are found.
func (pq *ProvinceQuery) Only(ctx context.Context) (*Province, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{province.Label}
	default:
		return nil, &NotSingularError{province.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *ProvinceQuery) OnlyX(ctx context.Context) *Province {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Province ID in the query.
// Returns a *NotSingularError when more than one Province ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *ProvinceQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{province.Label}
	default:
		err = &NotSingularError{province.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *ProvinceQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Provinces.
func (pq *ProvinceQuery) All(ctx context.Context) ([]*Province, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryAll)
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Province, *ProvinceQuery]()
	return withInterceptors[[]*Province](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *ProvinceQuery) AllX(ctx context.Context) []*Province {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Province IDs.
func (pq *ProvinceQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryIDs)
	if err = pq.Select(province.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *ProvinceQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *ProvinceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryCount)
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*ProvinceQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *ProvinceQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *ProvinceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryExist)
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *ProvinceQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProvinceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *ProvinceQuery) Clone() *ProvinceQuery {
	if pq == nil {
		return nil
	}
	return &ProvinceQuery{
		config:        pq.config,
		ctx:           pq.ctx.Clone(),
		order:         append([]province.OrderOption{}, pq.order...),
		inters:        append([]Interceptor{}, pq.inters...),
		predicates:    append([]predicate.Province{}, pq.predicates...),
		withDistricts: pq.withDistricts.Clone(),
		withCities:    pq.withCities.Clone(),
		withCountry:   pq.withCountry.Clone(),
		withTenders:   pq.withTenders.Clone(),
		withArea:      pq.withArea.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithDistricts tells the query-builder to eager-load the nodes that are connected to
// the "districts" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithDistricts(opts ...func(*DistrictQuery)) *ProvinceQuery {
	query := (&DistrictClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withDistricts = query
	return pq
}

// WithCities tells the query-builder to eager-load the nodes that are connected to
// the "cities" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithCities(opts ...func(*CityQuery)) *ProvinceQuery {
	query := (&CityClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withCities = query
	return pq
}

// WithCountry tells the query-builder to eager-load the nodes that are connected to
// the "country" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithCountry(opts ...func(*CountryQuery)) *ProvinceQuery {
	query := (&CountryClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withCountry = query
	return pq
}

// WithTenders tells the query-builder to eager-load the nodes that are connected to
// the "tenders" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithTenders(opts ...func(*TenderQuery)) *ProvinceQuery {
	query := (&TenderClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withTenders = query
	return pq
}

// WithArea tells the query-builder to eager-load the nodes that are connected to
// the "area" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithArea(opts ...func(*AreaQuery)) *ProvinceQuery {
	query := (&AreaClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withArea = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Province.Query().
//		GroupBy(province.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *ProvinceQuery) GroupBy(field string, fields ...string) *ProvinceGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProvinceGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = province.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Province.Query().
//		Select(province.FieldCreatedAt).
//		Scan(ctx, &v)
func (pq *ProvinceQuery) Select(fields ...string) *ProvinceSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &ProvinceSelect{ProvinceQuery: pq}
	sbuild.label = province.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProvinceSelect configured with the given aggregations.
func (pq *ProvinceQuery) Aggregate(fns ...AggregateFunc) *ProvinceSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *ProvinceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !province.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *ProvinceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Province, error) {
	var (
		nodes       = []*Province{}
		_spec       = pq.querySpec()
		loadedTypes = [5]bool{
			pq.withDistricts != nil,
			pq.withCities != nil,
			pq.withCountry != nil,
			pq.withTenders != nil,
			pq.withArea != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Province).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Province{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withDistricts; query != nil {
		if err := pq.loadDistricts(ctx, query, nodes,
			func(n *Province) { n.Edges.Districts = []*District{} },
			func(n *Province, e *District) { n.Edges.Districts = append(n.Edges.Districts, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withCities; query != nil {
		if err := pq.loadCities(ctx, query, nodes,
			func(n *Province) { n.Edges.Cities = []*City{} },
			func(n *Province, e *City) { n.Edges.Cities = append(n.Edges.Cities, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withCountry; query != nil {
		if err := pq.loadCountry(ctx, query, nodes, nil,
			func(n *Province, e *Country) { n.Edges.Country = e }); err != nil {
			return nil, err
		}
	}
	if query := pq.withTenders; query != nil {
		if err := pq.loadTenders(ctx, query, nodes,
			func(n *Province) { n.Edges.Tenders = []*Tender{} },
			func(n *Province, e *Tender) { n.Edges.Tenders = append(n.Edges.Tenders, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withArea; query != nil {
		if err := pq.loadArea(ctx, query, nodes, nil,
			func(n *Province, e *Area) { n.Edges.Area = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range pq.withNamedDistricts {
		if err := pq.loadDistricts(ctx, query, nodes,
			func(n *Province) { n.appendNamedDistricts(name) },
			func(n *Province, e *District) { n.appendNamedDistricts(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range pq.withNamedCities {
		if err := pq.loadCities(ctx, query, nodes,
			func(n *Province) { n.appendNamedCities(name) },
			func(n *Province, e *City) { n.appendNamedCities(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range pq.withNamedTenders {
		if err := pq.loadTenders(ctx, query, nodes,
			func(n *Province) { n.appendNamedTenders(name) },
			func(n *Province, e *Tender) { n.appendNamedTenders(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range pq.loadTotal {
		if err := pq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *ProvinceQuery) loadDistricts(ctx context.Context, query *DistrictQuery, nodes []*Province, init func(*Province), assign func(*Province, *District)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Province)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(district.FieldProvinceID)
	}
	query.Where(predicate.District(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(province.DistrictsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProvinceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "province_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *ProvinceQuery) loadCities(ctx context.Context, query *CityQuery, nodes []*Province, init func(*Province), assign func(*Province, *City)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Province)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(city.FieldProvinceID)
	}
	query.Where(predicate.City(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(province.CitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProvinceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "province_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *ProvinceQuery) loadCountry(ctx context.Context, query *CountryQuery, nodes []*Province, init func(*Province), assign func(*Province, *Country)) error {
	ids := make([]xid.ID, 0, len(nodes))
	nodeids := make(map[xid.ID][]*Province)
	for i := range nodes {
		fk := nodes[i].CountryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(country.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "country_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (pq *ProvinceQuery) loadTenders(ctx context.Context, query *TenderQuery, nodes []*Province, init func(*Province), assign func(*Province, *Tender)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Province)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tender.FieldProvinceID)
	}
	query.Where(predicate.Tender(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(province.TendersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProvinceID
		if fk == nil {
			return fmt.Errorf(`foreign-key "province_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "province_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *ProvinceQuery) loadArea(ctx context.Context, query *AreaQuery, nodes []*Province, init func(*Province), assign func(*Province, *Area)) error {
	ids := make([]xid.ID, 0, len(nodes))
	nodeids := make(map[xid.ID][]*Province)
	for i := range nodes {
		if nodes[i].AreaID == nil {
			continue
		}
		fk := *nodes[i].AreaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(area.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "area_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pq *ProvinceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *ProvinceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(province.Table, province.Columns, sqlgraph.NewFieldSpec(province.FieldID, field.TypeString))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, province.FieldID)
		for i := range fields {
			if fields[i] != province.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pq.withCountry != nil {
			_spec.Node.AddColumnOnce(province.FieldCountryID)
		}
		if pq.withArea != nil {
			_spec.Node.AddColumnOnce(province.FieldAreaID)
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *ProvinceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(province.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = province.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedDistricts tells the query-builder to eager-load the nodes that are connected to the "districts"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithNamedDistricts(name string, opts ...func(*DistrictQuery)) *ProvinceQuery {
	query := (&DistrictClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if pq.withNamedDistricts == nil {
		pq.withNamedDistricts = make(map[string]*DistrictQuery)
	}
	pq.withNamedDistricts[name] = query
	return pq
}

// WithNamedCities tells the query-builder to eager-load the nodes that are connected to the "cities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithNamedCities(name string, opts ...func(*CityQuery)) *ProvinceQuery {
	query := (&CityClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if pq.withNamedCities == nil {
		pq.withNamedCities = make(map[string]*CityQuery)
	}
	pq.withNamedCities[name] = query
	return pq
}

// WithNamedTenders tells the query-builder to eager-load the nodes that are connected to the "tenders"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (pq *ProvinceQuery) WithNamedTenders(name string, opts ...func(*TenderQuery)) *ProvinceQuery {
	query := (&TenderClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if pq.withNamedTenders == nil {
		pq.withNamedTenders = make(map[string]*TenderQuery)
	}
	pq.withNamedTenders[name] = query
	return pq
}

// ProvinceGroupBy is the group-by builder for Province entities.
type ProvinceGroupBy struct {
	selector
	build *ProvinceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *ProvinceGroupBy) Aggregate(fns ...AggregateFunc) *ProvinceGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *ProvinceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, ent.OpQueryGroupBy)
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProvinceQuery, *ProvinceGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *ProvinceGroupBy) sqlScan(ctx context.Context, root *ProvinceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProvinceSelect is the builder for selecting fields of Province entities.
type ProvinceSelect struct {
	*ProvinceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *ProvinceSelect) Aggregate(fns ...AggregateFunc) *ProvinceSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *ProvinceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, ent.OpQuerySelect)
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProvinceQuery, *ProvinceSelect](ctx, ps.ProvinceQuery, ps, ps.inters, v)
}

func (ps *ProvinceSelect) sqlScan(ctx context.Context, root *ProvinceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
