// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cscd-bds/store/ent/opportunity"
	"cscd-bds/store/ent/schema"
	"cscd-bds/store/ent/schema/xid"
	"cscd-bds/store/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	opportunityMixin := schema.Opportunity{}.Mixin()
	opportunityMixinFields0 := opportunityMixin[0].Fields()
	_ = opportunityMixinFields0
	opportunityMixinFields1 := opportunityMixin[1].Fields()
	_ = opportunityMixinFields1
	opportunityFields := schema.Opportunity{}.Fields()
	_ = opportunityFields
	// opportunityDescCreatedAt is the schema descriptor for created_at field.
	opportunityDescCreatedAt := opportunityMixinFields1[0].Descriptor()
	// opportunity.DefaultCreatedAt holds the default value on creation for the created_at field.
	opportunity.DefaultCreatedAt = opportunityDescCreatedAt.Default.(func() time.Time)
	// opportunityDescUpdatedAt is the schema descriptor for updated_at field.
	opportunityDescUpdatedAt := opportunityMixinFields1[1].Descriptor()
	// opportunity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	opportunity.DefaultUpdatedAt = opportunityDescUpdatedAt.Default.(func() time.Time)
	// opportunity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	opportunity.UpdateDefaultUpdatedAt = opportunityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// opportunityDescID is the schema descriptor for id field.
	opportunityDescID := opportunityMixinFields0[0].Descriptor()
	// opportunity.DefaultID holds the default value on creation for the id field.
	opportunity.DefaultID = opportunityDescID.Default.(func() xid.ID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() xid.ID)
}
