/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authImport } from './routes/__auth'
import { Route as authdashboardImport } from './routes/__auth/__dashboard'
import { Route as authdashboardmapImport } from './routes/__auth/__dashboard/__map'
import { Route as authportalPortalIndexImport } from './routes/__auth/__portal/portal/index'
import { Route as authdashboardmapIndexImport } from './routes/__auth/__dashboard/__map/index'
import { Route as authportalPortalPlotsImport } from './routes/__auth/__portal/portal/plots'
import { Route as authportalPortalCustomersImport } from './routes/__auth/__portal/portal/customers'
import { Route as authportalPortalTendersIndexImport } from './routes/__auth/__portal/portal/tenders.index'
import { Route as authportalPortalTendersIdImport } from './routes/__auth/__portal/portal/tenders.$id'
import { Route as authportalPortaladminUsersImport } from './routes/__auth/__portal/portal/__admin/users'

// Create Virtual Routes

const LogoutLazyImport = createFileRoute('/logout')()
const LoginLazyImport = createFileRoute('/login')()
const AccessDeniedLazyImport = createFileRoute('/access-denied')()
const authportalLazyImport = createFileRoute('/__auth/__portal')()
const authdashboardmapTendersLazyImport = createFileRoute(
  '/__auth/__dashboard/__map/tenders',
)()
const authportalPortalTendersNewLazyImport = createFileRoute(
  '/__auth/__portal/portal/tenders/new',
)()

// Create/Update Routes

const LogoutLazyRoute = LogoutLazyImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AccessDeniedLazyRoute = AccessDeniedLazyImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/access-denied.lazy').then((d) => d.Route))

const authRoute = authImport
  .update({
    id: '/__auth',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/__auth.lazy').then((d) => d.Route))

const authportalLazyRoute = authportalLazyImport
  .update({
    id: '/__portal',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth/__portal.lazy').then((d) => d.Route))

const authdashboardRoute = authdashboardImport
  .update({
    id: '/__dashboard',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth/__dashboard.lazy').then((d) => d.Route))

const authdashboardmapRoute = authdashboardmapImport
  .update({
    id: '/__map',
    getParentRoute: () => authdashboardRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__dashboard/__map.lazy').then((d) => d.Route),
  )

const authportalPortalIndexRoute = authportalPortalIndexImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => authportalLazyRoute,
} as any)

const authdashboardmapIndexRoute = authdashboardmapIndexImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => authdashboardmapRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__dashboard/__map/index.lazy').then((d) => d.Route),
  )

const authdashboardmapTendersLazyRoute = authdashboardmapTendersLazyImport
  .update({
    id: '/tenders',
    path: '/tenders',
    getParentRoute: () => authdashboardmapRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__dashboard/__map/tenders.lazy').then(
      (d) => d.Route,
    ),
  )

const authportalPortalPlotsRoute = authportalPortalPlotsImport
  .update({
    id: '/portal/plots',
    path: '/portal/plots',
    getParentRoute: () => authportalLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__portal/portal/plots.lazy').then((d) => d.Route),
  )

const authportalPortalCustomersRoute = authportalPortalCustomersImport
  .update({
    id: '/portal/customers',
    path: '/portal/customers',
    getParentRoute: () => authportalLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__portal/portal/customers.lazy').then(
      (d) => d.Route,
    ),
  )

const authportalPortalTendersIndexRoute = authportalPortalTendersIndexImport
  .update({
    id: '/portal/tenders/',
    path: '/portal/tenders/',
    getParentRoute: () => authportalLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__portal/portal/tenders.index.lazy').then(
      (d) => d.Route,
    ),
  )

const authportalPortalTendersNewLazyRoute = authportalPortalTendersNewLazyImport
  .update({
    id: '/portal/tenders/new',
    path: '/portal/tenders/new',
    getParentRoute: () => authportalLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__portal/portal/tenders.new.lazy').then(
      (d) => d.Route,
    ),
  )

const authportalPortalTendersIdRoute = authportalPortalTendersIdImport
  .update({
    id: '/portal/tenders/$id',
    path: '/portal/tenders/$id',
    getParentRoute: () => authportalLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__portal/portal/tenders.$id.lazy').then(
      (d) => d.Route,
    ),
  )

const authportalPortaladminUsersRoute = authportalPortaladminUsersImport
  .update({
    id: '/portal/__admin/users',
    path: '/portal/users',
    getParentRoute: () => authportalLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/__auth/__portal/portal/__admin/users.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/__auth/__dashboard': {
      id: '/__auth/__dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authdashboardImport
      parentRoute: typeof authImport
    }
    '/__auth/__portal': {
      id: '/__auth/__portal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authportalLazyImport
      parentRoute: typeof authImport
    }
    '/__auth/__dashboard/__map': {
      id: '/__auth/__dashboard/__map'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authdashboardmapImport
      parentRoute: typeof authdashboardImport
    }
    '/__auth/__portal/portal/customers': {
      id: '/__auth/__portal/portal/customers'
      path: '/portal/customers'
      fullPath: '/portal/customers'
      preLoaderRoute: typeof authportalPortalCustomersImport
      parentRoute: typeof authportalLazyImport
    }
    '/__auth/__portal/portal/plots': {
      id: '/__auth/__portal/portal/plots'
      path: '/portal/plots'
      fullPath: '/portal/plots'
      preLoaderRoute: typeof authportalPortalPlotsImport
      parentRoute: typeof authportalLazyImport
    }
    '/__auth/__dashboard/__map/tenders': {
      id: '/__auth/__dashboard/__map/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof authdashboardmapTendersLazyImport
      parentRoute: typeof authdashboardmapImport
    }
    '/__auth/__dashboard/__map/': {
      id: '/__auth/__dashboard/__map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authdashboardmapIndexImport
      parentRoute: typeof authdashboardmapImport
    }
    '/__auth/__portal/portal/': {
      id: '/__auth/__portal/portal/'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof authportalPortalIndexImport
      parentRoute: typeof authportalLazyImport
    }
    '/__auth/__portal/portal/__admin/users': {
      id: '/__auth/__portal/portal/__admin/users'
      path: '/portal/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof authportalPortaladminUsersImport
      parentRoute: typeof authportalLazyImport
    }
    '/__auth/__portal/portal/tenders/$id': {
      id: '/__auth/__portal/portal/tenders/$id'
      path: '/portal/tenders/$id'
      fullPath: '/portal/tenders/$id'
      preLoaderRoute: typeof authportalPortalTendersIdImport
      parentRoute: typeof authportalLazyImport
    }
    '/__auth/__portal/portal/tenders/new': {
      id: '/__auth/__portal/portal/tenders/new'
      path: '/portal/tenders/new'
      fullPath: '/portal/tenders/new'
      preLoaderRoute: typeof authportalPortalTendersNewLazyImport
      parentRoute: typeof authportalLazyImport
    }
    '/__auth/__portal/portal/tenders/': {
      id: '/__auth/__portal/portal/tenders/'
      path: '/portal/tenders'
      fullPath: '/portal/tenders'
      preLoaderRoute: typeof authportalPortalTendersIndexImport
      parentRoute: typeof authportalLazyImport
    }
  }
}

// Create and export the route tree

interface authdashboardmapRouteChildren {
  authdashboardmapTendersLazyRoute: typeof authdashboardmapTendersLazyRoute
  authdashboardmapIndexRoute: typeof authdashboardmapIndexRoute
}

const authdashboardmapRouteChildren: authdashboardmapRouteChildren = {
  authdashboardmapTendersLazyRoute: authdashboardmapTendersLazyRoute,
  authdashboardmapIndexRoute: authdashboardmapIndexRoute,
}

const authdashboardmapRouteWithChildren =
  authdashboardmapRoute._addFileChildren(authdashboardmapRouteChildren)

interface authdashboardRouteChildren {
  authdashboardmapRoute: typeof authdashboardmapRouteWithChildren
}

const authdashboardRouteChildren: authdashboardRouteChildren = {
  authdashboardmapRoute: authdashboardmapRouteWithChildren,
}

const authdashboardRouteWithChildren = authdashboardRoute._addFileChildren(
  authdashboardRouteChildren,
)

interface authportalLazyRouteChildren {
  authportalPortalCustomersRoute: typeof authportalPortalCustomersRoute
  authportalPortalPlotsRoute: typeof authportalPortalPlotsRoute
  authportalPortalIndexRoute: typeof authportalPortalIndexRoute
  authportalPortaladminUsersRoute: typeof authportalPortaladminUsersRoute
  authportalPortalTendersIdRoute: typeof authportalPortalTendersIdRoute
  authportalPortalTendersNewLazyRoute: typeof authportalPortalTendersNewLazyRoute
  authportalPortalTendersIndexRoute: typeof authportalPortalTendersIndexRoute
}

const authportalLazyRouteChildren: authportalLazyRouteChildren = {
  authportalPortalCustomersRoute: authportalPortalCustomersRoute,
  authportalPortalPlotsRoute: authportalPortalPlotsRoute,
  authportalPortalIndexRoute: authportalPortalIndexRoute,
  authportalPortaladminUsersRoute: authportalPortaladminUsersRoute,
  authportalPortalTendersIdRoute: authportalPortalTendersIdRoute,
  authportalPortalTendersNewLazyRoute: authportalPortalTendersNewLazyRoute,
  authportalPortalTendersIndexRoute: authportalPortalTendersIndexRoute,
}

const authportalLazyRouteWithChildren = authportalLazyRoute._addFileChildren(
  authportalLazyRouteChildren,
)

interface authRouteChildren {
  authdashboardRoute: typeof authdashboardRouteWithChildren
  authportalLazyRoute: typeof authportalLazyRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authdashboardRoute: authdashboardRouteWithChildren,
  authportalLazyRoute: authportalLazyRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof authdashboardmapRouteWithChildren
  '/access-denied': typeof AccessDeniedLazyRoute
  '/login': typeof LoginLazyRoute
  '/logout': typeof LogoutLazyRoute
  '/portal/customers': typeof authportalPortalCustomersRoute
  '/portal/plots': typeof authportalPortalPlotsRoute
  '/tenders': typeof authdashboardmapTendersLazyRoute
  '/': typeof authdashboardmapIndexRoute
  '/portal': typeof authportalPortalIndexRoute
  '/portal/users': typeof authportalPortaladminUsersRoute
  '/portal/tenders/$id': typeof authportalPortalTendersIdRoute
  '/portal/tenders/new': typeof authportalPortalTendersNewLazyRoute
  '/portal/tenders': typeof authportalPortalTendersIndexRoute
}

export interface FileRoutesByTo {
  '': typeof authportalLazyRouteWithChildren
  '/access-denied': typeof AccessDeniedLazyRoute
  '/login': typeof LoginLazyRoute
  '/logout': typeof LogoutLazyRoute
  '/portal/customers': typeof authportalPortalCustomersRoute
  '/portal/plots': typeof authportalPortalPlotsRoute
  '/tenders': typeof authdashboardmapTendersLazyRoute
  '/': typeof authdashboardmapIndexRoute
  '/portal': typeof authportalPortalIndexRoute
  '/portal/users': typeof authportalPortaladminUsersRoute
  '/portal/tenders/$id': typeof authportalPortalTendersIdRoute
  '/portal/tenders/new': typeof authportalPortalTendersNewLazyRoute
  '/portal/tenders': typeof authportalPortalTendersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/__auth': typeof authRouteWithChildren
  '/access-denied': typeof AccessDeniedLazyRoute
  '/login': typeof LoginLazyRoute
  '/logout': typeof LogoutLazyRoute
  '/__auth/__dashboard': typeof authdashboardRouteWithChildren
  '/__auth/__portal': typeof authportalLazyRouteWithChildren
  '/__auth/__dashboard/__map': typeof authdashboardmapRouteWithChildren
  '/__auth/__portal/portal/customers': typeof authportalPortalCustomersRoute
  '/__auth/__portal/portal/plots': typeof authportalPortalPlotsRoute
  '/__auth/__dashboard/__map/tenders': typeof authdashboardmapTendersLazyRoute
  '/__auth/__dashboard/__map/': typeof authdashboardmapIndexRoute
  '/__auth/__portal/portal/': typeof authportalPortalIndexRoute
  '/__auth/__portal/portal/__admin/users': typeof authportalPortaladminUsersRoute
  '/__auth/__portal/portal/tenders/$id': typeof authportalPortalTendersIdRoute
  '/__auth/__portal/portal/tenders/new': typeof authportalPortalTendersNewLazyRoute
  '/__auth/__portal/portal/tenders/': typeof authportalPortalTendersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/access-denied'
    | '/login'
    | '/logout'
    | '/portal/customers'
    | '/portal/plots'
    | '/tenders'
    | '/'
    | '/portal'
    | '/portal/users'
    | '/portal/tenders/$id'
    | '/portal/tenders/new'
    | '/portal/tenders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/access-denied'
    | '/login'
    | '/logout'
    | '/portal/customers'
    | '/portal/plots'
    | '/tenders'
    | '/'
    | '/portal'
    | '/portal/users'
    | '/portal/tenders/$id'
    | '/portal/tenders/new'
    | '/portal/tenders'
  id:
    | '__root__'
    | '/__auth'
    | '/access-denied'
    | '/login'
    | '/logout'
    | '/__auth/__dashboard'
    | '/__auth/__portal'
    | '/__auth/__dashboard/__map'
    | '/__auth/__portal/portal/customers'
    | '/__auth/__portal/portal/plots'
    | '/__auth/__dashboard/__map/tenders'
    | '/__auth/__dashboard/__map/'
    | '/__auth/__portal/portal/'
    | '/__auth/__portal/portal/__admin/users'
    | '/__auth/__portal/portal/tenders/$id'
    | '/__auth/__portal/portal/tenders/new'
    | '/__auth/__portal/portal/tenders/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
  AccessDeniedLazyRoute: typeof AccessDeniedLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  LogoutLazyRoute: typeof LogoutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
  AccessDeniedLazyRoute: AccessDeniedLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  LogoutLazyRoute: LogoutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__auth",
        "/access-denied",
        "/login",
        "/logout"
      ]
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/__dashboard",
        "/__auth/__portal"
      ]
    },
    "/access-denied": {
      "filePath": "access-denied.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/logout": {
      "filePath": "logout.lazy.tsx"
    },
    "/__auth/__dashboard": {
      "filePath": "__auth/__dashboard.tsx",
      "parent": "/__auth",
      "children": [
        "/__auth/__dashboard/__map"
      ]
    },
    "/__auth/__portal": {
      "filePath": "__auth/__portal.lazy.tsx",
      "parent": "/__auth",
      "children": [
        "/__auth/__portal/portal/customers",
        "/__auth/__portal/portal/plots",
        "/__auth/__portal/portal/",
        "/__auth/__portal/portal/__admin/users",
        "/__auth/__portal/portal/tenders/$id",
        "/__auth/__portal/portal/tenders/new",
        "/__auth/__portal/portal/tenders/"
      ]
    },
    "/__auth/__dashboard/__map": {
      "filePath": "__auth/__dashboard/__map.tsx",
      "parent": "/__auth/__dashboard",
      "children": [
        "/__auth/__dashboard/__map/tenders",
        "/__auth/__dashboard/__map/"
      ]
    },
    "/__auth/__portal/portal/customers": {
      "filePath": "__auth/__portal/portal/customers.tsx",
      "parent": "/__auth/__portal"
    },
    "/__auth/__portal/portal/plots": {
      "filePath": "__auth/__portal/portal/plots.tsx",
      "parent": "/__auth/__portal"
    },
    "/__auth/__dashboard/__map/tenders": {
      "filePath": "__auth/__dashboard/__map/tenders.lazy.tsx",
      "parent": "/__auth/__dashboard/__map"
    },
    "/__auth/__dashboard/__map/": {
      "filePath": "__auth/__dashboard/__map/index.tsx",
      "parent": "/__auth/__dashboard/__map"
    },
    "/__auth/__portal/portal/": {
      "filePath": "__auth/__portal/portal/index.tsx",
      "parent": "/__auth/__portal"
    },
    "/__auth/__portal/portal/__admin/users": {
      "filePath": "__auth/__portal/portal/__admin/users.tsx",
      "parent": "/__auth/__portal"
    },
    "/__auth/__portal/portal/tenders/$id": {
      "filePath": "__auth/__portal/portal/tenders.$id.tsx",
      "parent": "/__auth/__portal"
    },
    "/__auth/__portal/portal/tenders/new": {
      "filePath": "__auth/__portal/portal/tenders.new.lazy.tsx",
      "parent": "/__auth/__portal"
    },
    "/__auth/__portal/portal/tenders/": {
      "filePath": "__auth/__portal/portal/tenders.index.tsx",
      "parent": "/__auth/__portal"
    }
  }
}
ROUTE_MANIFEST_END */
