/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as mapImport } from './routes/__map'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const authLazyImport = createFileRoute('/__auth')()
const mapProvinceLazyImport = createFileRoute('/__map/province')()
const mapMapLazyImport = createFileRoute('/__map/map')()
const mapAreaMapLazyImport = createFileRoute('/__map/area-map')()
const map3LazyImport = createFileRoute('/__map/3')()
const map2LazyImport = createFileRoute('/__map/2')()
const mapProvincesIndexLazyImport = createFileRoute('/__map/provinces/')()
const mapAreasIndexLazyImport = createFileRoute('/__map/areas/')()
const mapAreasAreaLazyImport = createFileRoute('/__map/areas/$area')()

// Create/Update Routes

const authLazyRoute = authLazyImport
  .update({
    id: '/__auth',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/__auth.lazy').then((d) => d.Route))

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const mapRoute = mapImport.update({
  id: '/__map',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const mapProvinceLazyRoute = mapProvinceLazyImport
  .update({
    id: '/province',
    path: '/province',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/province.lazy').then((d) => d.Route))

const mapMapLazyRoute = mapMapLazyImport
  .update({
    id: '/map',
    path: '/map',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/map.lazy').then((d) => d.Route))

const mapAreaMapLazyRoute = mapAreaMapLazyImport
  .update({
    id: '/area-map',
    path: '/area-map',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/area-map.lazy').then((d) => d.Route))

const map3LazyRoute = map3LazyImport
  .update({
    id: '/3',
    path: '/3',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/3.lazy').then((d) => d.Route))

const map2LazyRoute = map2LazyImport
  .update({
    id: '/2',
    path: '/2',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/2.lazy').then((d) => d.Route))

const mapProvincesIndexLazyRoute = mapProvincesIndexLazyImport
  .update({
    id: '/provinces/',
    path: '/provinces/',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() =>
    import('./routes/__map/provinces/index.lazy').then((d) => d.Route),
  )

const mapAreasIndexLazyRoute = mapAreasIndexLazyImport
  .update({
    id: '/areas/',
    path: '/areas/',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/areas/index.lazy').then((d) => d.Route))

const mapAreasAreaLazyRoute = mapAreasAreaLazyImport
  .update({
    id: '/areas/$area',
    path: '/areas/$area',
    getParentRoute: () => mapRoute,
  } as any)
  .lazy(() => import('./routes/__map/areas/$area.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__map': {
      id: '/__map'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mapImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLazyImport
      parentRoute: typeof rootRoute
    }
    '/__map/2': {
      id: '/__map/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof map2LazyImport
      parentRoute: typeof mapImport
    }
    '/__map/3': {
      id: '/__map/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof map3LazyImport
      parentRoute: typeof mapImport
    }
    '/__map/area-map': {
      id: '/__map/area-map'
      path: '/area-map'
      fullPath: '/area-map'
      preLoaderRoute: typeof mapAreaMapLazyImport
      parentRoute: typeof mapImport
    }
    '/__map/map': {
      id: '/__map/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof mapMapLazyImport
      parentRoute: typeof mapImport
    }
    '/__map/province': {
      id: '/__map/province'
      path: '/province'
      fullPath: '/province'
      preLoaderRoute: typeof mapProvinceLazyImport
      parentRoute: typeof mapImport
    }
    '/__map/areas/$area': {
      id: '/__map/areas/$area'
      path: '/areas/$area'
      fullPath: '/areas/$area'
      preLoaderRoute: typeof mapAreasAreaLazyImport
      parentRoute: typeof mapImport
    }
    '/__map/areas/': {
      id: '/__map/areas/'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof mapAreasIndexLazyImport
      parentRoute: typeof mapImport
    }
    '/__map/provinces/': {
      id: '/__map/provinces/'
      path: '/provinces'
      fullPath: '/provinces'
      preLoaderRoute: typeof mapProvincesIndexLazyImport
      parentRoute: typeof mapImport
    }
  }
}

// Create and export the route tree

interface mapRouteChildren {
  map2LazyRoute: typeof map2LazyRoute
  map3LazyRoute: typeof map3LazyRoute
  mapAreaMapLazyRoute: typeof mapAreaMapLazyRoute
  mapMapLazyRoute: typeof mapMapLazyRoute
  mapProvinceLazyRoute: typeof mapProvinceLazyRoute
  mapAreasAreaLazyRoute: typeof mapAreasAreaLazyRoute
  mapAreasIndexLazyRoute: typeof mapAreasIndexLazyRoute
  mapProvincesIndexLazyRoute: typeof mapProvincesIndexLazyRoute
}

const mapRouteChildren: mapRouteChildren = {
  map2LazyRoute: map2LazyRoute,
  map3LazyRoute: map3LazyRoute,
  mapAreaMapLazyRoute: mapAreaMapLazyRoute,
  mapMapLazyRoute: mapMapLazyRoute,
  mapProvinceLazyRoute: mapProvinceLazyRoute,
  mapAreasAreaLazyRoute: mapAreasAreaLazyRoute,
  mapAreasIndexLazyRoute: mapAreasIndexLazyRoute,
  mapProvincesIndexLazyRoute: mapProvincesIndexLazyRoute,
}

const mapRouteWithChildren = mapRoute._addFileChildren(mapRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof authLazyRoute
  '/about': typeof AboutRoute
  '/2': typeof map2LazyRoute
  '/3': typeof map3LazyRoute
  '/area-map': typeof mapAreaMapLazyRoute
  '/map': typeof mapMapLazyRoute
  '/province': typeof mapProvinceLazyRoute
  '/areas/$area': typeof mapAreasAreaLazyRoute
  '/areas': typeof mapAreasIndexLazyRoute
  '/provinces': typeof mapProvincesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof authLazyRoute
  '/about': typeof AboutRoute
  '/2': typeof map2LazyRoute
  '/3': typeof map3LazyRoute
  '/area-map': typeof mapAreaMapLazyRoute
  '/map': typeof mapMapLazyRoute
  '/province': typeof mapProvinceLazyRoute
  '/areas/$area': typeof mapAreasAreaLazyRoute
  '/areas': typeof mapAreasIndexLazyRoute
  '/provinces': typeof mapProvincesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__map': typeof mapRouteWithChildren
  '/about': typeof AboutRoute
  '/__auth': typeof authLazyRoute
  '/__map/2': typeof map2LazyRoute
  '/__map/3': typeof map3LazyRoute
  '/__map/area-map': typeof mapAreaMapLazyRoute
  '/__map/map': typeof mapMapLazyRoute
  '/__map/province': typeof mapProvinceLazyRoute
  '/__map/areas/$area': typeof mapAreasAreaLazyRoute
  '/__map/areas/': typeof mapAreasIndexLazyRoute
  '/__map/provinces/': typeof mapProvincesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/2'
    | '/3'
    | '/area-map'
    | '/map'
    | '/province'
    | '/areas/$area'
    | '/areas'
    | '/provinces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/2'
    | '/3'
    | '/area-map'
    | '/map'
    | '/province'
    | '/areas/$area'
    | '/areas'
    | '/provinces'
  id:
    | '__root__'
    | '/'
    | '/__map'
    | '/about'
    | '/__auth'
    | '/__map/2'
    | '/__map/3'
    | '/__map/area-map'
    | '/__map/map'
    | '/__map/province'
    | '/__map/areas/$area'
    | '/__map/areas/'
    | '/__map/provinces/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mapRoute: typeof mapRouteWithChildren
  AboutRoute: typeof AboutRoute
  authLazyRoute: typeof authLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mapRoute: mapRouteWithChildren,
  AboutRoute: AboutRoute,
  authLazyRoute: authLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__map",
        "/about",
        "/__auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__map": {
      "filePath": "__map.tsx",
      "children": [
        "/__map/2",
        "/__map/3",
        "/__map/area-map",
        "/__map/map",
        "/__map/province",
        "/__map/areas/$area",
        "/__map/areas/",
        "/__map/provinces/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/__auth": {
      "filePath": "__auth.lazy.tsx"
    },
    "/__map/2": {
      "filePath": "__map/2.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/3": {
      "filePath": "__map/3.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/area-map": {
      "filePath": "__map/area-map.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/map": {
      "filePath": "__map/map.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/province": {
      "filePath": "__map/province.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/areas/$area": {
      "filePath": "__map/areas/$area.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/areas/": {
      "filePath": "__map/areas/index.lazy.tsx",
      "parent": "/__map"
    },
    "/__map/provinces/": {
      "filePath": "__map/provinces/index.lazy.tsx",
      "parent": "/__map"
    }
  }
}
ROUTE_MANIFEST_END */
